import { query } from '@/lib/db';

export async function POST(req) {
    try {
        const { contentType, contentId, reason, description, reporterId } = await req.json();

        if (!contentType || !contentId || !reason || !reporterId) {
            return Response.json({ error: 'Missing required fields' }, { status: 400 });
        }

        // Validate content type
        if (!['BLOG', 'COMMENT'].includes(contentType)) {
            return Response.json({ error: 'Invalid content type' }, { status: 400 });
        }

        // Check if content exists
        let contentExists = false;
        if (contentType === 'BLOG') {
            const blog = await query('SELECT id FROM blogs WHERE id = ?', [contentId]);
            contentExists = blog.length > 0;
        } else if (contentType === 'COMMENT') {
            const comment = await query('SELECT id FROM comments WHERE id = ?', [contentId]);
            contentExists = comment.length > 0;
        }

        if (!contentExists) {
            return Response.json({ error: 'Content not found' }, { status: 404 });
        }

        // Check if user already reported this content
        const existing = await query(`
      SELECT id FROM content_reports 
      WHERE reporter_id = ? AND content_type = ? AND content_id = ? AND status = 'PENDING'
    `, [reporterId, contentType, contentId]);

        if (existing.length > 0) {
            return Response.json({ error: 'You have already reported this content' }, { status: 400 });
        }

        // Create report
        const result = await query(`
      INSERT INTO content_reports (reporter_id, content_type, content_id, reason, description, status)
      VALUES (?, ?, ?, ?, ?, 'PENDING')
    `, [reporterId, contentType, contentId, reason, description || null]);

        // Optional: Notify admin (if you have notification system)
        await notifyAdmins(contentType, contentId, reason);

        return Response.json({
            success: true,
            reportId: null, // UUID generated by DB
            message: 'Thank you for your report. We will review it shortly.'
        });
    } catch (error) {
        console.error('Reports POST error:', error);
        return Response.json({ error: 'Internal server error' }, { status: 500 });
    }
}

// Helper function to notify admins (placeholder)
async function notifyAdmins(contentType, contentId, reason) {
    // This could send an email or create admin notifications
    console.log(`New report: ${contentType} #${contentId} - Reason: ${reason}`);
}