import { query } from '@/lib/db';
import { generateToken } from '@/lib/auth';
import { NextResponse } from 'next/server';

export async function GET(req) {
    const { searchParams } = new URL(req.url);
    const code = searchParams.get('code');

    if (!code) {
        return NextResponse.redirect(new URL('/login?error=no_code', req.url));
    }

    try {
        const tokenResponse = await fetch('https://oauth2.googleapis.com/token', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
                code,
                client_id: process.env.GOOGLE_CLIENT_ID,
                client_secret: process.env.GOOGLE_CLIENT_SECRET,
                redirect_uri: process.env.GOOGLE_REDIRECT_URI,
                grant_type: 'authorization_code',
            }),
        });

        const tokens = await tokenResponse.json();

        const userResponse = await fetch('https://www.googleapis.com/oauth2/v2/userinfo', {
            headers: { Authorization: `Bearer ${tokens.access_token}` },
        });

        const userInfo = await userResponse.json();

        // Check if user exists
        let user = await query('SELECT * FROM public_users WHERE email = ?', [userInfo.email]);

        if (user.length === 0) {
            // Create new user — UUID generated by MySQL, fetch it back
            await query(
                `INSERT INTO public_users (email, name, avatar_url, password_hash, email_verified_at) 
                 VALUES (?, ?, ?, '', NOW())`,
                [userInfo.email, userInfo.name, userInfo.picture]
            );
            const newUser = await query('SELECT id, email, name FROM public_users WHERE email = ?', [userInfo.email]);
            user = newUser[0];
        } else {
            await query('UPDATE public_users SET avatar_url = ? WHERE email = ?', [userInfo.picture, userInfo.email]);
            user = user[0];
        }

        const token = generateToken(user.id, 'public');

        // NextResponse.redirect supports .cookies
        const response = NextResponse.redirect(new URL('/', req.url));
        response.cookies.set('token', token, {
            httpOnly: true,
            secure: process.env.NODE_ENV === 'production',
            sameSite: 'strict',
            maxAge: 7 * 24 * 60 * 60,
            path: '/',
        });

        return response;
    } catch (error) {
        console.error('Google callback error:', error);
        return NextResponse.redirect(new URL('/login?error=auth_failed', req.url));
    }
}